feature/253 Router confirmation cancel triggering route event
NaluKit/nalu pull request #254
Opened 2022-03-04 12:32 UTC by masterdany88

2022-03-04 17:41 UTC, philkohl commented on nalu/src/main/java/com/github/nalukit/nalu/client/internal/route/AbstractRouter.java
> +                              fireRouterStateEvent(RouterState.ROUTING_ABORTED,
Please add a new RouteState called ROUTING_CANCELED_BY_USER

2022-03-04 17:42 UTC, philkohl requested changes
see comment

2022-03-04 21:53 UTC, masterdany88 commented
Ok Enum type added. Still We miss previous route path before You trigger routing.

2022-03-05 10:43 UTC, FrankHossfeld approved these changes

2022-03-05 10:45 UTC, FrankHossfeld approved these changes

2022-03-05 10:46 UTC, merged

2022-03-05 10:54 UTC, masterdany88 commented
Did You test it? In event There is wrong url.

2022-03-05 11:42 UTC, FrankHossfeld commented
Yeap, tested it. It looks good. The cancel event get fired and the route inside the event is the route, that is canceled by the user. So, nothing wrong.

2022-03-05 11:58 UTC, FrankHossfeld commented
see my comment inside the issue.