Build release with actions
NaluKit/nalu pull request #314
Opened 2023-05-07 16:22 UTC by philkohl

2023-05-07 19:25 UTC, FrankHossfeld requested changes

2023-05-07 19:25 UTC, FrankHossfeld commented on .github/workflows/build.yaml
> +        run: mvn deploy -ntp -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD_NALUKIT_GITHUB_USER }} -DskipTests -Daether.checksums.algorithms=MD5
hier fehlt das Profil release : -P release

2023-05-07 19:25 UTC, FrankHossfeld commented on .github/workflows/build.yaml
Das hier:
 - name: Upload OWASP results
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: OWASP report
          path: ${{github.workspace}}/reports

sollte nach:

       - name: Upload OWASP results
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: OWASP report
          path: ${{github.workspace}}/**/reports/dependency-check-report.html

geändert werden

2023-05-07 19:42 UTC, philkohl commented on .github/workflows/build.yaml
> +        run: mvn deploy -ntp -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD_NALUKIT_GITHUB_USER }} -DskipTests -Daether.checksums.algorithms=MD5
done

2023-05-07 19:43 UTC, philkohl commented on .github/workflows/build.yaml
done

2023-05-07 19:50 UTC, FrankHossfeld approved these changes

2023-05-08 04:21 UTC, FrankHossfeld commented
This PR will solve https://github.com/NaluKit/nalu/pull/311

2023-05-08 07:16 UTC, merged